.PHONY: clean All

All:
	@echo "----------Building project:[ Leilao - Debug ]----------"
	@cd "Leilao" && "$(MAKE)" -f  "Leilao.mk"
clean:
	@echo "----------Cleaning project:[ Leilao - Debug ]----------"
	@cd "Leilao" && "$(MAKE)" -f  "Leilao.mk" clean
