.PHONY: clean All

All:
	@echo "----------Building project:[ forca - Debug ]----------"
	@cd "forca" && "$(MAKE)" -f  "forca.mk"
clean:
	@echo "----------Cleaning project:[ forca - Debug ]----------"
	@cd "forca" && "$(MAKE)" -f  "forca.mk" clean
