.PHONY: clean All

All:
	@echo "----------Building project:[ coffe_shop - Debug ]----------"
	@cd "coffe_shop" && "$(MAKE)" -f  "coffe_shop.mk"
clean:
	@echo "----------Cleaning project:[ coffe_shop - Debug ]----------"
	@cd "coffe_shop" && "$(MAKE)" -f  "coffe_shop.mk" clean
